name: GO build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
        
    name: Run build

    steps:
      # ============= InvisiRisk Setup =============
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          app_token: ${{ secrets.IR_API_KEY }}
      # ============= InvisiRisk Setup End =============

      # Checkout the code
      - uses: actions/checkout@v4

      # ============= Cache Go Modules =============
      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      # ============= Cache Go Modules End =============

      # Install dependencies (go mod tidy to ensure modules are correct)
      - name: Install dependencies
        run: go mod tidy

      # Build the project
      - name: Build
        run: go build -v ./...

      # Run tests
      - name: Run tests
        run: go test -v ./...
        continue-on-error: true  # Allow tests to fail without breaking the workflow

      # ============= InvisiRisk Cleanup =============
      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"
      # ============= InvisiRisk Cleanup End =============
